name: CI

on:
  push:
    branches:
      - 'master'
      - 'pymbar4'
      - 'gha'
  pull_request:
    branches:
      - 'master'
      - 'pymbar4'
      - 'gha'
  schedule:
    # Nightly Tests
    - cron: '0 0 * * *'

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8]
    env:
      PYVER: ${{ matrix.python-version }}
      CI_OS: ${{ matrix.os }}
      PACKAGE: "pymbar"

    steps:
    - name: Checkout the code
      uses: actions/checkout@v1

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Fix conda in MacOS
      shell: bash
      if: startsWith(matrix.os, 'macOS')
      run: |
        sudo chown -R $(id -u):$(id -g) ${CONDA}

    - name: Create environment for package
      shell: bash
      run: |
        . devtools/github-actions/initialize_conda.sh
        conda activate
        conda info
        python devtools/scripts/create_conda_env.py -n=test -p=$PYVER devtools/conda-envs/test_env.yaml

    - name: Install package
      shell: bash
      run: |
        . devtools/github-actions/initialize_conda.sh
        conda activate test
        python -m pip install . --no-deps
        conda list --show-channel-urls

    - name: Run tests (pytest)
      shell: bash
      run: |
        . devtools/github-actions/initialize_conda.sh
        conda activate test
        pytest -v --cov=$PACKAGE --cov-report=xml --color=yes --doctest-modules $PACKAGE/

    - name: Run examples
      shell: bash
      run: |
        . devtools/github-actions/initialize_conda.sh
        conda activate test
        ### constant-force-optical-trap
        cd examples/constant-force-optical-trap
        python extract-data.py
        python force-bias-optical-trap.py
        ### harmonic-oscillators
        cd ../harmonic-oscillators
        python harmonic-oscillators.py
        python harmonic-oscillators-distributions.py
        cd ../heat-capacity
        python heat-capacity.py -b 2
        ### parallel-tempering-2dpmf
        cd ../parallel-tempering-2dpmf
        python parallel-tempering-2dpmf.py
        ### umbrella-sampling-pmf
        cd ../umbrella-sampling-pmf
        python umbrella-sampling.py
        python umbrella-sampling-smoothpmf.py

    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        yml: ./.codecov.yml

  lint-format:
    runs-on: ubuntu-latest
    env:
      CI_OS: ubuntu-latest
      PACKAGE: "pymbar"
      PYVER: "3.7"

    steps:
    - name: Checkout the code
      uses: actions/checkout@v1

    - name: Install linter and formatter
      shell: bash
      run: |
        . devtools/github-actions/initialize_conda.sh
        conda activate
        python devtools/scripts/create_conda_env.py -n=test -p=$PYVER devtools/conda-envs/test_env.yaml
        conda activate test
        conda install pylint black

    - name: Run pylint
      shell: bash
      run: |
        . devtools/github-actions/initialize_conda.sh
        conda activate test
        pylint $PACKAGE/

    # TODO: Remove --exclude pymbar/old_mbar.py after deprecation
    - name: Run black check
      shell: bash
      if: always()
      run: |
        . devtools/github-actions/initialize_conda.sh
        conda activate test
        black --check -l 99 $PACKAGE/ --exclude pymbar/old_mbar.py
